[package]
name = "chronos"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dotenvy = "0.15.7"
sqlx = { version = "0.8.4", features = ["runtime-tokio", "postgres", "migrate", "uuid", "time"] }
tokio = {version = "1.47.1", features = ["full"]}
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
